config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :course_ratings
  resources :publications
  resources :courses
  resources :students
  resources :instructors

   root 'courses#index'

end

app/models/student.rb
class Student < ActiveRecord::Base
	

	has_many :registration
	has_many :course_ratings
	has_many :courses, through: :registration


	validates_presence_of :name, :email, :mobile, :major
	validates_uniqueness_of :email, :name
	validates_length_of :mobile, is: 10
	validates_numericality_of :mobile
	validates_format_of :email, with:/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :email, :mobile, :major, course_ids: [])
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<div class = "container">
  <div class = "col-md-3">
    <%= form_for(@student) do |f| %>
      <% if @student.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

          <ul>
          <% @student.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field" class = "form-group" >
        <%= f.label :name %><br>
        <%= f.text_field :name, class: "form-control"%>
      </div>
      <div class="field" class = "form-group">
        <%= f.label :email %><br>
        <%= f.text_field :email, class: "form-control" %>
      </div>
      <div class="field" class = "form-group">
        <%= f.label :mobile %><br>
        <%= f.text_field :mobile, class: "form-control" %>
      </div>
      <div class="field" class = "form-group">
        <%= f.label :major %><br>
        <%= f.text_field :major, class: "form-control" %>
      </div>
      <div class="field" class = "form-group">
        <%= f.label :Select_Course %><br/>
        <%= f.collection_check_boxes :course_ids, Course.all, :id, :name, class: "form-control"  do |student|%>
          <label>
              <%= student.check_box %>
              <%= student.text %>
          </label>
        <%end%>
      </div>
      <div class="actions">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/students/edit.html.erb
<div class = "container">
<%= render 'form' %>
</div>

app/views/students/index.html.erb
<div class = "container">
    <h3><i class = "glyphicon glyphicon-th-list"></i>Listing Students</h3>
    <div class = "col-md-8">
        <table class = "table table-striped" id = "studentList">
          <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Mobile</th>
              <th>Major</th>
              <th>Actions</th>
            </tr>
          </thead>

          <tbody>
            <% @students.each do |student| %>
              <tr>
                <td><%= link_to student.name, student %></td>
                <td><%= student.email %></td>
                <td><%= student.mobile %></td>
                <td><%= student.major %></td>
                <td>
                  <% if user_signed_in?%>
                      <% if can? :update, student %>
                          <%= link_to edit_student_path(student) do  %>
                            <i class = "glyphicon glyphicon-pencil"></i>
                            <% end %>
                      <% end %>
                      <% if can? :destroy, student %>
                        <%= link_to student, method: :delete, data: { confirm: 'Are you sure?' } do %>
                            <i class="glyphicon glyphicon-trash"></i>
                            <%end%>
                      <% end %>
               <% end %>
              </td>
              </tr>
              <% end %>
          </tbody>
        </table>

        <br>

        <% if user_signed_in? && (can? :create, Student.new)%>
          <%= link_to 'New Student', new_student_path %>
        <% end %>
    </div>
</div>

app/views/students/new.html.erb
<div class = "conatiner">
<%= render 'form' %>
</div>

app/views/students/show.html.erb
<div class = "container">
	<div class = "col-md-4">
		<p>
		  <strong>Name:</strong>
		  <%= @student.name %>
		</p>

		<p>
		  <strong>Email:</strong>
		  <%= @student.email %>
		</p>

		<p>
		  <strong>Mobile:</strong>
		  <%= @student.mobile %>
		</p>

		<p>
		  <strong>Major:</strong>
		  <%= @student.major %>
		</p>
		<p>
			<h2>Course Enrolled</h2>
			<% if @student.courses.empty? %>
				<p>No course Enrolled </p>
			<% else %>
				<ul>
				<% @student.courses.each do |course| %>
					<li><%= link_to course.name, course_path(course.id) %></li>
				<% end %>
				</ul>
			<% end %>
		
		</p>
	</div>
</div>