config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :course_ratings
  resources :publications
  resources :courses
  resources :students
  resources :instructors

   root 'courses#index'

end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
	has_many :courses
	has_many :publications


	validates_presence_of :name, :email, :bio, :mobile
	validates_uniqueness_of :name, :email
	validates_numericality_of :mobile
	validates_length_of :mobile, is: 10
	validates_format_of :email, with:/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]

  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.all
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to @instructor, notice: 'Instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to @instructor, notice: 'Instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'Instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:name, :email, :bio, :mobile)
    end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<div class = "container" >
<div class = "col-md-3">
    <%= form_for(@instructor) do |f| %>
      <% if @instructor.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

          <ul>
          <% @instructor.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field" class = "form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: "form-control"%>
      </div>
      <div class="field" class = "form-group">
        <%= f.label :email %><br>
        <%= f.text_field :email, class: "form-control" %>
      </div>
      <div class="field" class = "form-group">
        <%= f.label :bio %><br>
        <%= f.text_area :bio, class: "form-control" %>
      </div>
      <div class="field" class = "form-group">
        <%= f.label :mobile %><br>
        <%= f.text_field :mobile, class: "form-control" %>
      </div></br>
      <div class="actions">
        <%= f.submit class: "btn btn-primary"%>
      </div>
    <% end %>
    </div>
</div>

app/views/instructors/edit.html.erb
<div class = "container">

<%= render 'form' %>
</div>

app/views/instructors/index.html.erb
<div class = "container">
<div class = "col-md-8">
    <h3><i class = "glyphicon glyphicon-th-list"></i>Listing Instructors</h3>

    <table class = "table table-hover" id = "instList" >
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Mobile</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @instructors.each do |instructor| %>
          <tr>
            <td><%= link_to instructor.name, instructor%></td>
            <td><%= instructor.email %></td>
            <td><%= instructor.mobile %></td>
            <td><% if user_signed_in?  %>
                  <% if can? :update, instructor %>
                    <%= link_to edit_instructor_path(instructor) do %>
                      <i class = "glyphicon glyphicon-pencil"></i>
                      <% end %>
                  <% end %>

                  <% if can? :destroy, instructor %>
                    <%= link_to instructor, method: :delete, data: { confirm: 'Are you sure?' } do %>
                      <i class="glyphicon glyphicon-trash"></i>
                    <% end %>
                  <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <% if user_signed_in? && (can? :create, Instructor.new)%>
      <%= link_to 'New Instructor', new_instructor_path %>
    <% end %>
</div>
</div>

app/views/instructors/new.html.erb
<div class = "container">
<%= render 'form' %>
</div>

app/views/instructors/show.html.erb
<div class = "container">
	<p>
	  <strong>Name:</strong>
	  <%= @instructor.name %>
	</p>

	<p>
	  <strong>Email:</strong>
	  <%= @instructor.email %>
	</p>

	<p>
	  <strong>Bio:</strong>
	  <%= @instructor.bio %>
	</p>

	<p>
	  <strong>Mobile:</strong>
	  <%= @instructor.mobile %>
	</p>	
</div>