config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :course_ratings
  resources :publications
  resources :courses
  resources :students
  resources :instructors

   root 'courses#index'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource

  before_action :set_course, only: [:show, :edit, :update, :destroy]



  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :instructor_id, :description)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<div class = "container"> 
  <div class = "col-md-3">
    <%= form_for(@course) do |f| %>
      <% if @course.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

          <ul>
          <% @course.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field" class = "form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: "form-control"%>
      </div>
      
      <div class="field" class = "form-group">
        <%= f.label :description %><br>
        <%= f.text_area :description, class: "form-control" %>
      </div>
      <div class="field" class = "form-group">
        <%= f.label :Instructor %><br>
        <%= f.collection_select :instructor_id, Instructor.all, :id, :name, {prompt: "Select Course"},{class: "form-control"} do |instructor| %>
          <label>
            <%= instructor.check_box %>
            <%= instructor.text %>
          </label>
      <% end %>
    
    
      </div> <br/>
      <div class="actions">
        <%= f.submit class:"btn btn-primary" %>
      </div>
    <% end %>
</div>
</div>

app/views/courses/edit.html.erb
<div class = "container">
<%= render 'form' %>
</div>

app/views/courses/index.html.erb
<div class = "container">
<div class = "col-md-6">
<h3><i class = "glyphicon glyphicon-th-list"></i>Listing Courses</h3>

<table class = "table table-striped" id = "courseList">
  <thead>
    <tr>
      <th>Name</th>
      <th>Instructor</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= link_to course.name, course%></td>
        <td><%= course.instructor.name %></td>
        <td><%= course.description %></td>
        <td>
          <% if user_signed_in? %>
            <% if can? :update, course %>
                <%= link_to edit_course_path(course) do  %>
                    <i class = "glyphicon glyphicon-pencil"></i>
                  <%end%>
            <% end %>
            <% if can? :destroy, course %>
                <%= link_to course,method: :delete, data: { confirm: 'Are you sure?' }  do %>
                    <i class="glyphicon glyphicon-trash"></i>
                  <% end %>
            <% end %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? && (can? :create, Course.new) %>
<%= link_to 'New Course', new_course_path %>
<% end %>
</div>
</div>

app/views/courses/new.html.erb
<div class = "container">
	<%= render 'form' %>
</div>

app/views/courses/show.html.erb
<div class = "container">

    <p>
      <strong>Name:</strong>
      <%= @course.name %>
    </p>

    <p>
      <strong>Instructor:</strong>
      <%= link_to @course.instructor.name, instructor_path(@course.instructor.id)%>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @course.description %>
    </p>
    <p>

    <% if user_signed_in? %>
       <h2>Student enrolled</h2>
      <% if @course.students.empty? %>
      	<p> No course enrolled </p> 
      <% else %>
      	<ul>
      		<% @course.students.each do |student| %>
      			<li><%= link_to student.name, student_path(student.id)%></li>
      		<% end %>
      	</ul>
      <% end %>
    <% end %>
    </p>
   
</div>